### ISSUE TITLE
Still works in 2022?

### ISSUE THREAD

**Issue by n3m** [Falconerd/discord-bot-github#100]
So, I tried setting it up yesterday for a private Github organization for a repo's releases.

The webhook is being called correctly as you can see in the following image
<img width="782" alt="image" src="https://user-images.githubusercontent.com/36679293/181513929-59458814-28ab-445a-9825-bcb636cbf129.png">

the server is responding with a `204`
<img width="787" alt="image" src="https://user-images.githubusercontent.com/36679293/181514063-e44a58c1-e960-4d0f-bc35-9d2192018d02.png">

but the Discord bot is not creating any new messages, even though it is setup with correctly with a secret and all.
This is the (raw) command that is being run on the server to setup the bot.

`/dbg-add org:ORGUSERNAME name:ORGPRIVATEREPO secret:CREATEDSECRET previews:False`

**Comment by zgurwitz** [comment]
I'm also getting a check next to my recent deliveries but am not getting a discord update. :(
