### ISSUE TITLE
Support for gitlab, gogs, private repository?

### ISSUE THREAD

**Issue by SloppierKitty7** [Falconerd/discord-bot-github#21]
In the tile

**Comment by Falconerd** [comment]
Private repos should work on GitHub. As for gitlab and gogs, I'll have to look into their APIs and see if they offer a similar webhook service.

**Comment by Falconerd** [comment]
For now, I am going to say that this is outside the scope of this particular project. I'm sure some talented people are already working on or perhaps may have even made bots for other platforms.

As I'm solely a GitHub user I can't commit my time to creating something for these other platforms.
