### ISSUE TITLE
Amazing: Just add "checks" subscription?

### ISSUE THREAD

**Issue by Akkadius** [Falconerd/discord-bot-github#22]
We're using this for the EQEmulator community discord, we've got this tied to our EQEmu/Server Github repo. We've heavily relied on travis-ci notifications to know that Linux builds have passed and we also use app-veyor, are we able to get build/check notifications into the channel as well once they have passed?

I'm not sure completely which push notification this is from Github cause its not clear in the documentation, but I'm sure it sends some sort of notification and as long as we could get this to push to discord, it would be amazing to know the checks have passed.

http://i.imgur.com/WDyiynV.png

Thanks!

**Comment by Falconerd** [comment]
Hey @Akkadius, glad you like the bot. I'll look into seeing if I can add this when I get some spare time. A bit flat out with work ATM.

**Comment by Akkadius** [comment]
Totally get it man. We're using it in the meantime, if you want to PM me at all I'm at: https://discord.gg/QHsm7CD

**Comment by Falconerd** [comment]
Hey @Akkadius, I just merged a PR into this repo and got this notification:

![](http://i.imgur.com/pcQwBEJ.png)

Are you guys not getting anything?

**Comment by Akkadius** [comment]
Yeah they are working now, you just need to make sure you webhook 'All' events apparently. All events seem to be pretty spammy as well too though, anyway to filter certain events? Thanks for this awesome bot. http://i.imgur.com/Ty3Z11l.png
