### ISSUE TITLE
Wiki Page edits results in printing the JSON or something

### ISSUE THREAD

**Issue by g33kidd** [Falconerd/discord-bot-github#23]
Basically what happened was, I edited a Wiki page and it displays the message: http://d.pr/i/16Ir7

**Comment by Falconerd** [comment]
Apologies for the late reply, that link is currently dead. Would you mind posting a different one?

**Comment by g33kidd** [comment]
Oops.. forgot to set it to "do not destroy this image"... No problem! Here's the new image.

http://d.pr/i/1edKn

**Comment by Falconerd** [comment]
Fixed by commit https://github.com/Falconerd/discord-bot-github/commit/895a7e2108401ab3066b0950e8f6e7387bd8f13b

Should now look like this ![Screenshot](http://i.imgur.com/K4HCI1S.png)

**<page name>:** <action>
