### ISSUE TITLE
Bot doesn't respond to any commands at all...

### ISSUE THREAD

**Issue by ForbodingAngel** [Falconerd/discord-bot-github#27]
https://i.imgur.com/1QcjAMz.png

https://i.imgur.com/4zMQ6YL.png

What gives? It responds to nothing. Repo webhook is set up and being delivered correctly, the bot is authorized... What's going on?

**Comment by Falconerd** [comment]
It seems there has been some critical issues causing the bot to crash over the last 24 hours. Looking into it now.

**Comment by knoxed** [comment]
Having the same issue

**Comment by Techbot121** [comment]
if it helps, the auth token for bot's need to have "bot" pre-pended now [see here](https://discordapp.com/developers/docs/reference#example-authorization-headers).

**Comment by pundurs** [comment]
Yes, issue exists, can confirm.

**Comment by LordMisfit** [comment]
yeah, I noticed the bot wasn't posting any updates on some of my repos, so I tried to readd one of them, and no response. :o

**Comment by ForbodingAngel** [comment]
Any news?

**Comment by knoxed** [comment]
@Falconerd Please can we get an update on this, it takes 5 minutes to fix this. Thanks :)

**Comment by Falconerd** [comment]
Sorry, I have been busy with work... I'm updating it now. Thanks for the help, guys.

**Comment by knoxed** [comment]
@Falconerd I tried running !dbg help in several channels to see if it's an issue with my permissions but it still does not output anything.

**Comment by LaP0573** [comment]
@Falconerd !dbg help seems to trigger the proper help response but the bot doesn't react to me opening or closing issues (I even tried readding it to the channel).

**Comment by Falconerd** [comment]
This should be working now, please let me know if there are any other problems related to the update... Cheers.
