### ISSUE TITLE
Question: Does this work with BitBucket commits as well?

### ISSUE THREAD

**Issue by Mesagoppinmypants** [Falconerd/discord-bot-github#31]
I was wondering if this would work with BitBucket commits as well?

**Comment by Falconerd** [comment]
Currently it doesn't, and I'm not sure if I should extend this project for that or create a separate one. The majority of the code could be the same, just the payload event code would be different.

**Comment by santiago26** [comment]
Please, consider this again, since you've decided to stop development of GH integration.
