### ISSUE TITLE
Bot doesn't post any repo updates

### ISSUE THREAD

**Issue by ZerataX** [Falconerd/discord-bot-github#33]
So I've added the webhook:

![github webhook](https://my.mixtape.moe/mippph.png)
and added a subscription to a channel:

![discord channel](https://my.mixtape.moe/wkilwp.png)

I even added an extra permission for the channel:
![discord permissions](https://my.mixtape.moe/zycllr.png)

but I still don't get any message when I update my repo.

**Edit:** Sorry, I forgot I had my images on a temporary image host. I'm probably missing something very obvious here, but thank you for your help.

**Comment by Falconerd** [comment]
Hi @ZerataX, those images are broken for me. If you could update them with working ones I will take a look into this when I home tomorrow.

**Comment by Falconerd** [comment]
Hey @ZerataX, so the problem you're having is that you just added the repo name without the user.

For example: `!dbg add zeratax/ebooks` should work for you.

On a sidenote, you've now made me aware that I should check to see if the subscription is valid before adding it, cheers.
