### ISSUE TITLE
Private repository

### ISSUE THREAD

**Issue by Lopez-i** [Falconerd/discord-bot-github#34]
Hi, how set up github bot for a private repository ?
thanks a lot for reply

**Comment by Falconerd** [comment]
Hi,@Lopez-i, private repositories can be set up in the same way as non-private repositories. Please see this issue for further information https://github.com/Falconerd/discord-bot-github/issues/30

**Comment by Falconerd** [comment]
Hi again @Lopez-i, I'm sorry. It seems I was mistaken. I have come to see that private repositories are currently not working, though they are planned for a future update. Please see #38 for information about it.

**Comment by Falconerd** [comment]
This should be fixed by #41 as soon as the live code is updated. Give or take 24h
