### ISSUE TITLE
Prevent the bot from previewing links

### ISSUE THREAD

**Issue by branden-akana** [Falconerd/discord-bot-github#39]
This is probably a personal taste thing, but I think the bot embedding _every single link_ is pretty spammy. 
Example:
![](http://i.imgur.com/6QwzCJ2.png)
(This is when I created an issue and labeled it at the same time)

I understand embedding can be turned off through disabling "link preview" through the user settings, but if this is something that wasn't intentional and you're interested in having it turned off just for the bot, the way to do that is to surround all the links the bot posts with `<>`.

**Comment by Falconerd** [comment]
Thanks for reporting this. I vaguely remember looking into it in November but can't remember any conclusion I came to. I'll look into it again.

I agree it is definitely spammy.

**Comment by depfryer** [comment]
for have only link change the link to <link> discord make all
for see the difference : http://image.noelshack.com/fichiers/2017/04/1485175765-nouvelle-image-bitmap.png
yep i custom discord

**Comment by Falconerd** [comment]
Sweet, that is easy enough

**Comment by depfryer** [comment]
;p markdown powa

**Comment by ivellios** [comment]
Hmm... it doesn't seem to be merged still... what is going on with this feature? I would love to have it, since right now after pushing 10+ commits the channel is in a mess.

**Comment by depfryer** [comment]
i'm not sure but  
add a Bool like `linkPreview` in the event 
with a option like `SetLinkPreview True/False`

and foreach Url add (already in event 
``` JS
const url = linkPreview ? '<'+ data.comment.html_url + '>'  : data.comment.html_url;
```

**Comment by ivellios** [comment]
yup, that might work as well... I will look in a free time. 

Anyway: looks like there's a branch for es6 rewrite of the code. Does anyone know when it is planned to be merged/released, so the herokuapp is updated? Or is this project abandoned and I will have to deploy it to my own host?

**Comment by ivellios** [comment]
OK, this is more complicated than I fought. `handleRequest` has no information on the channel, so I am not able to pull the setting data from Mongo I think. I will stick with this PR I posted above for now ;) It's better than nothing :)

**Comment by depfryer** [comment]
i remember with this https://gist.github.com/jagrosh/5b1761213e33fc5b54ec7f6379034a22
so just host you're own
