### ISSUE TITLE
"1 new commit by Your Name" - user is not called "Your Name"

### ISSUE THREAD

**Issue by lemtzas** [Falconerd/discord-bot-github#42]
![image](https://cloud.githubusercontent.com/assets/1063171/21292359/3160bc20-c4b7-11e6-9ae2-240e3d530e8e.png)

[The commit in question.](https://github.com/josefnpat/pico8collab16/commit/26dee37)

**Comment by lemtzas** [comment]
Potentially relevant:

`release()` uses `data.release.author.login` [line](https://github.com/Falconerd/discord-bot-github/blob/develop-es6/src/events.js#L147)

`push()` uses `commit.author.name` [line](https://github.com/Falconerd/discord-bot-github/blob/develop-es6/src/events.js#L119)

**Comment by Falconerd** [comment]
Thanks for reporting this issue. I'll look into it.
