### ISSUE TITLE
Make a Python Version.

### ISSUE THREAD

**Issue by AraHaan** [Falconerd/discord-bot-github#45]
I know a lot of python bots devs who use discord.py would love something like this for their python bots where it listens to the bot's repo. My bot is one of them so that way I can tell when someone opens an pull request, an issue, or when a collaborator pushes to it so that way I know I got to update something on my copy of my bot. Think of this as an important thing for command extension bots.

The thing is that I have no idea how to code such thing. Unless someone like Danny (Rapptz) can make a cog for it on his bot so that way I can barrow that cog. I did that for his repl to be on my bot as well.

**Comment by Falconerd** [comment]
Sorry, I don't have much Python experience, so I've got no plans to do this.
