### ISSUE TITLE
Does it work for private repositories?

### ISSUE THREAD

**Issue by n0minal** [Falconerd/discord-bot-github#47]
Hi, I installed the bot on my server following the readme.md but when I try to add my private repository with !dbg add <repository> it says the repository does not exists, if I try with --private flag nothing happens. Could you please help me?

**Comment by Falconerd** [comment]
You must add the private flag after the command, as such: `!dbg add user/repo --private`

**Comment by n0minal** [comment]
when I do it nothing happens as I stated in the first post, I'm using Discord's default webhook for it but I really would like to have a bot doing it

**Comment by Zim104** [comment]
I can confirm the same behavior for my private repo.  The bot does not respond to !dbg add user/repo --private

**Comment by macalinao** [comment]
I can confirm the same behavior for my private repo. The bot does not respond to !dbg add user/repo --private

**Comment by waffln** [comment]
Yup. Same here. --private doesn't change anything. Without it, the bot says "Repository not found."

**Comment by n0minal** [comment]
Nice workaround, still looking for a fix, I don't really like Discord's github bot cause it does not print the whole commit message, only few

**Comment by prithvi2k2** [comment]
Is there a fix for this without making it public? after 3years...

**Comment by UzBestDeveloper** [comment]
Hi from 2021 :-)

**Comment by Falconerd** [comment]
> 
> 
> Is there a fix for this without making it public? after 3years...

There is :). See the README
