### ISSUE TITLE
Issue request: Filtering of events

### ISSUE THREAD

**Issue by Zamiell** [Falconerd/discord-bot-github#53]
I like that the bot announces brand new issues. That's really useful!

What's not so useful is that:
* it announces when an issue is edited (even when someone adds something trivial, like punctuation)
* it announces when a tag is added to an issue (which will often occur after the issue is already created and conveys no new addition information)

Thus, the bot can get quite spammy! How about a way to disable things? Like how about a `toggle` command like so:

```
!dbg toggle issue-edit
!dbg toggle issue-tag
```

By default, it can be toggled on or off, depending on what the user's prefers. And when toggled off, it just won't broadcast these types of events. (Of course, the default value for the toggles can be whatever you think is best.)

Finally, I want to say thanks for the excellent bot, and thanks for hosting it free of charge! I really appreciate it.

**Comment by Falconerd** [comment]
I think this is covered by the webhook event selection. Thanks for the kind words.
