### ISSUE TITLE
Coppy

### ISSUE THREAD

**Issue by Taelyn** [Falconerd/discord-bot-github#63]
Is it possible to get a coppy of the bot so i can host it my self?

**Comment by felixfong227** [comment]
👋 @Taelyn 

What do you meant by

> copy of the bot so that you can host your own

**Comment by Taelyn** [comment]
What i mean is to get a working coppy of the code so i can host it on my own dedicated server for my self

**Comment by felixfong227** [comment]
I think you can just simply clone the repo down to your local development machine

```
$ git clone git@github.com:Falconerd/discord-bot-github.git
```

And what looks like the `master` is actually not a stable branch, so switching from `master` branch to `develop-es6` branch seems to be the most logical option here
