### ISSUE TITLE
Flaw or feature? Pinging users on Discord from GitHub

### ISSUE THREAD

**Issue by RossComputerGuy** [Falconerd/discord-bot-github#64]
If you do `\@rolename` you can get the string needed on discord to mention groups, I use this to notify users who have a specific role but this could be bad to have.

**Comment by Zamiell** [comment]
I consider this a flaw. The bot should scrub any text with "@" and replace it with "at". Otherwise you could open up a million issues with the word "@everyone" in it in order to spam every single member of a discord.

**Comment by SpaceboyRoss01** [comment]
Being able to filter it to allow only specific groups should be what should be done.
