### ISSUE TITLE
GitHub bot simply prints "message" to the console

### ISSUE THREAD

**Issue by controversial** [Falconerd/discord-bot-github#7]
I followed the local setup instructions, and successfully installed the module. I created a token with the following privileges:

I also filled out a `config.json` like so:

```json
{
"interval":5000,
"email": "johndoe@example.com",
"password": "password",
"token": "token",
"avatar": "iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAYAAACqaXHeAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAyRpVFh0WE1MOmNvbS5hZG9iZS54bXAAAAAAADw/eHBhY2tldCBiZWdpbj0i77u/IiBpZD0iVzVNME1wQ2VoaUh6cmVTek5UY3prYzlkIj8+IDx4OnhtcG1ldGEgeG1sbnM6eD0iYWRvYmU6bnM6bWV0YS8iIHg6eG1wdGs9IkFkb2JlIFhNUCBDb3JlIDUuMy1jMDExIDY2LjE0NTY2MSwgMjAxMi8wMi8wNi0xNDo1NjoyNyAgICAgICAgIj4gPHJkZjpSREYgeG1sbnM6cmRmPSJodHRwOi8vd3d3LnczLm9yZy8xOTk5LzAyLzIyLXJkZi1zeW50YXgtbnMjIj4gPHJkZjpEZXNjcmlwdGlvbiByZGY6YWJvdXQ9IiIgeG1sbnM6eG1wPSJodHRwOi8vbnMuYWRvYmUuY29tL3hhcC8xLjAvIiB4bWxuczp4bXBNTT0iaHR0cDovL25zLmFkb2JlLmNvbS94YXAvMS4wL21tLyIgeG1sbnM6c3RSZWY9Imh0dHA6Ly9ucy5hZG9iZS5jb20veGFwLzEuMC9zVHlwZS9SZXNvdXJjZVJlZiMiIHhtcDpDcmVhdG9yVG9vbD0iQWRvYmUgUGhvdG9zaG9wIENTNiAoTWFjaW50b3NoKSIgeG1wTU06SW5zdGFuY2VJRD0ieG1wLmlpZDpFNTE3OEEyRTk5QTAxMUUyOUExNUJDMTA0NkE4OTA0RCIgeG1wTU06RG9jdW1lbnRJRD0ieG1wLmRpZDpFNTE3OEEyRjk5QTAxMUUyOUExNUJDMTA0NkE4OTA0RCI+IDx4bXBNTTpEZXJpdmVkRnJvbSBzdFJlZjppbnN0YW5jZUlEPSJ4bXAuaWlkOkU1MTc4QTJDOTlBMDExRTI5QTE1QkMxMDQ2QTg5MDREIiBzdFJlZjpkb2N1bWVudElEPSJ4bXAuZGlkOkU1MTc4QTJEOTlBMDExRTI5QTE1QkMxMDQ2QTg5MDREIi8+IDwvcmRmOkRlc2NyaXB0aW9uPiA8L3JkZjpSREY+IDwveDp4bXBtZXRhPiA8P3hwYWNrZXQgZW5kPSJyIj8+FYrpWAAABrNJREFUeNrkW2lsVFUUvjMWirYUkS5BXApUa2vd6gL+wAWjoP5RiW2EUBajAiqSuPADQ0w1UUQTrcFAUUSJEKriEuMWFKuJIElFSS24YNpQK6WoBbuAktbva880M8O8vnfevJm+CSf5cme599xzvnfffffce17AJFjycnLzUVwDXAgUAucBY4BMIEOqdQIdwJ/Az4J64OvWtoONibQvkACHgyiuBe4CbgLOjVNlE/AZsAmoBSE9viQAjueieBCYC5yVoAvWDKwHqkBEmy8IgON09lHgXmCESY4cBaqBlSCieUgIgOPDUCwBngBOM0MjXdL/CyDiv6QRAOcvR7EBKDL+kD3AbJBQl1AC4DjrLwaeBYYbf8m/ciu+BCJ6PScAzp+K4nXgTuNveQuYAxK6PSMAzo9C8TFwtUkN2Q7cDBIOx02AOP8FUGpSSzgf3GBHQsDGec7unwOTTWrKDiGhS02ATHjvALeb1JZ3gRlWE+MpVq0yMzIekRk/1YWP6o7Ors5vHI8AXH1Odl8BaTbKrwd4j10MTAduS8JqkKvA94BPgN0A56htNm2OMyDDKNhuSwCcT5dIrMBG6S4oLI1qezqKBcBjwGiPHW8HVgCr0W97VL/fobjMpv2vQAnaHgv/MdYVXurAeSNPhggRw56BQatRVgL3A0H5+xDwI8Dw9g/5Hlq+clmdDYwF8iV0zpb/GP2tApZHOx4m2xwQUCC+VVqOABg+AUUDkO6AgHkwaL2DJXORxPVNylUnw+gpXObaLXFRlxHoaw7U8uoXQ99vViNgqUPnKQfsKojhdW7GuxDW5JUtIuni432hH4JhLJ7Dq6qwcZiPZnpNXDJPfI0kQEJbjVM5PiIgW3nhlkQQILH9LGWnV/iIAK0ts8TngREwDchVKrnKRwRobckVnwcIKFcq4ONrkY8IWBT2SHUq5eEE3Khs/CRm6Z1+8V5sqVQ26/M5gHuhSJ79TqUFmIhOj/ppwQ8/Rshqb5yiWXFQFhsaWeU352UU0KaXlc2mBI1+Y3OzjyO/Gm2kSAIKFQ2awfQ+v3oP23gL/K5oUhh0GPiEZG8KxP97FHULgsqwtTUFCDioqHsGCRipaHA8BQjQrAcyg4roj5KVAgSMUtRNDyqVj0wBAlQ2koBuRf3xKUBAvqJuN1eCrYpAiHNAltNjpyFYDfL47oix38wdmDA5AvYr+kjzWRgcLVcqnKfsJwGNyk5u9TEBtyjrNwaVgRClTPKA/Db8aVOZslkDG2nD2vEuOkqGlLmYpHcGJLlJu8LjtvJFgx06Jvnq8xC33gUBeUE4waWjduua5wdVPrr6VS6cr6PvoXv5Ixed3g3mH/fB1V9OW1w07fM5IEouUEZR4bIWWJzsTRJ55r8I3ONSRRFs3hsIU8hkgkkulf0CPAx8qElQcuk4beYp9Epgoks138LOvqSPgfyAzIwMZlnFSobgIegc4H3gH6AkxmKDub9Mjb0DeoYDrZ1dne0eO14AvfPx8RXgAYaycahbBvt+GLgFpIM0md3PjqrMTMxpYKxB6p1v+s/n7bbSuMCqldmZyc+fRh9ND+IsAxrmG3C3qtj0J1uP84hLrnwnwJbjEQRIxzw0XB2jER93C9Bog9TjsRgzLpzuJr0BzHV6e8gwf9XoziqdCv1YE/oSTQBHwfem/3w+5syPxuukLtfdO0zk+WIs+YuPKLQ7ohzyWTIix3joPPMTLg1d/Yg5gIL7ogf32U/4WGGhYDr+34J6bUALPpPA62w6XYMOP9BaCv3HoD/PeJubODN6U/eEq4cKTIurttpBAZ4L+87TmKdtOt0ah8FbPXS+WnyLEKskqUy5FaweM5dA2e6w+pNkZuajhfMD3/zYBfDKb3Y6+cWwgytOL7bh98nQ73BEgHReIvd4Roy/a6Cs3CRYJOnq7zjV8HWcybC33mpLLKZIA84FPRYhcSokUNL2Civnjd0MjoZbUCy0+PtNkDDD5wQsFB8sxWm2+GJZd8eSt4HnZXnZ66Nb4CHYYxuxat4XmI1inbHeczskq77DMrK4z8AgK3+Q/L5EEMBn/PzQos0zAsQgvg5XY3TpNKOTSAD3NsrQX63TBqq9PVHM9NgvfXi/06ZSjfNqAoQEHj9Pled+pw8cpw2co6aKbSoJxDlJnYniKdP/sqSVrrEw7IBL/TnG+rSXEy7fYVoG/S1uffDkzVEYypB1qewJRCdb5rp9yxN6mQDZFmOS2wisCIXo8Yin7w7LiKiQEcFYfhOMnBmnzo1CLIO09Qyt47niJxDQ29trTmY56Qn4X4ABAFR7IoDmVT5NAAAAAElFTkSuQmCC",

"subscriptions": [
    {
      "repository": "The-Penultimate-Defenestrator/SocialNPHS",
      "servers": [
        {
          "id": "173617917445931009",
          "invite": "https://discord.gg/invite_id",
          "channels": [
            {
              "name": "general",
              "events": [
                "Push",
                "PullRequest",
                "Issues"
              ]
            }
          ]
        }
      ]
    }
]


}
```

`avatar` is a base64-encoded copy of the `GitHub-Mark-64px.png` distributed from https://github.com/logos, and my access token has the following privileges:

![](http://i.imgur.com/b7GEnFe.png)

Anywho, I started the bot, and it began to run. However, when I create an issue, the bot simply posts 

> Message!

like so:
![](http://i.imgur.com/7RMwGSc.png)

What is up with this? Isn't the bot supposed to post more detailed messages than this? Could it have anything to do with the fact that my repository is private?

**Comment by Falconerd** [comment]
Yes, it's meant to post more detailed messages than that. I'll have to do some testing with private repositories.

**Comment by The-Penultimate-Defenestrator** [comment]
Ok. If you're not on a paid GitHub plan, I'd be happy to create an empty
private repository and invite you as a collaborator, simply for testing
purposes.

**Comment by The-Penultimate-Defenestrator** [comment]
@Falconerd Do you plan to look into this soon? If not, I may start working on a PR. Where in this repo does the text `Message!` come from? Is it a default from a lower-level library?

**Comment by Falconerd** [comment]
Hey @The-Penultimate-Defenestrator, I finally got some time to look at this. I checked with the readme, and it seems that the "Issues" events are not yet supported. I'll be putting out an update in the next day to address this.

**Comment by The-Penultimate-Defenestrator** [comment]
Oh, that's why. Anyway, for now, I just built myself an alternative. My
version is just a Flask app sitting on my server that sends a request to
the discord API URL. It works well for my purposes. I may very well go back
to this as more functionality is added.

**Comment by controversial** [comment]
Cool. I'll give this another try, now.

**Comment by Falconerd** [comment]
I'm actually working on a full rewrite as a proper Discord bot, hoping to have that out in a week or so. I just closed issue as I was doing some organisation and didn't see any point keeping it open.

**Comment by controversial** [comment]
Awesome! Wait, a full discord bot like it responds to messages? It doesn't
really need to listen for messages otherwise, just webhook events...

**Comment by Falconerd** [comment]
Well, the new version doesn't use a config file. It instead lets you add subscriptions and stores them in an mlab instance.

Example: Typing `!dbg add controversial/wikipedia-map` in a channel would then create a document in the database akin to this one:

```{
    "_id": {
        "$oid": "5790659634908300110cf79c"
    },
    "repo": "falconerd/discord-bot-github",
    "channelId": "133848740971806720"
}```

You can also add a personal access token for private repos, and they will be stored in a separate collection. This does mean that I'd have access to people's tokens, and they may see that as a security risk. They can always download the bot and create their own discord bot with this source code and that'd be fine.

**Comment by controversial** [comment]
Hmm. Are read-only tokens possible?

Could you authenticate like CI services do, and use OAuth to create a
webhook for your server?

**Comment by Falconerd** [comment]
Yeah, that is what I'm doing. The bot doesn't need to write anything.

**Comment by Falconerd** [comment]
I'll try to get a working version out in the next week then I'm happy for people to poke holes in the security and I'll fix them up.

**Comment by Falconerd** [comment]
Wait yes, I just remembered... It's been over a week since I looked at this.

Currently you have to add the webhook to the repository! I'll test if this works for private repos. In which case there's no need to add tokens.

**Comment by controversial** [comment]
Cool. Do you welcome contributions? I think a webhook would be faster, more
reliable, and safer than any kind of token.

If you had your server hold an index of which channels in which servers
were "tracking" each repo, then you could have a global endpoint at which
your server received webhook events (which GitHub sends out as soon as
changes are made, automatically), then your server could receive these
events and dispatch them by sending a message to each of the servers
watching that repo.

This would be much more reliable and secure than polling with an access
token. What do you think of that?

**Comment by Falconerd** [comment]
Yes, I do welcome contributions and I'm also in agreement that using webhooks is a much better idea than polling. I've implemented that in the new version. 

Give me a little bit to think about this and restructure and I'll update you...

**Comment by controversial** [comment]
Cool! Let me know.

**Comment by Falconerd** [comment]
I think this version is actually working...

If you set a webhook to https://discordbotgithub.herokuapp.com and enable the bot in your server by clicking this link https://discordapp.com/oauth2/authorize?client_id=193000403632128013&scope=bot

You should be able to add a subscription with the command `!dbg add user/repo` and then create a test issue or something to test it...

In any case I'm going to clean up the directory as I've added a bunch of tools which I'm not using anymore.

**Comment by controversial** [comment]
Cool! I'll try it out.
