### ISSUE TITLE
Repository not found

### ISSUE THREAD

**Issue by grillo78** [Falconerd/discord-bot-github#71]
I'm getting always this error but I have all set properly, I tried with another repository that I added to other server in the past without problems and this time I got the same error
![imagen](https://user-images.githubusercontent.com/19859573/73616579-71756d00-4615-11ea-9eed-1470a3819207.png)

**Comment by JordanLozinski** [comment]
If it's private I think you need to add ` --private` at the end of the command.
This isnt anywhere in the documentation but it's in the source code.

**Comment by excalibr23** [comment]
I'm having the same issue and get an error when I use --private.

**Comment by booleans-oss** [comment]
These commands need one argument: **the repo's name** but not the repo's link. 
```js
request(`https://github.com/${repo}`, (err, res) => {
```
I'll be working to have the option of putting both link or name

**Comment by hjoseph96** [comment]
I get repository not found for:

`!dbg add hjoseph96/codename_mystery_babylon`

&& I get an error for:

`!dbg add hjoseph96/codename_mystery_babylon --private`

**Comment by Falconerd** [comment]
Now instead of using the private flag, you should be able to specify a secret. Instructions are in the README.
