### ISSUE TITLE
Add support for Bot Users

### ISSUE THREAD

**Issue by branden-akana** [Falconerd/discord-bot-github#8]
via the [`loginWithToken`](http://discordjs.readthedocs.io/en/latest/docs_client.html#loginwithtoken-token-email-password-callback) function in discord.js. It would also require you to depend on a much newer version of the discord.js package. 

I've already done it very lazily on [my fork](https://github.com/branden-akana/discord-bot-github) (it uses your email as the bot token) but I'm sure there's a much better way to add this in.

Nothing serious or anything, but it allowed me to make my bots actually be recognized as bots
![](http://i.imgur.com/KbAA7Vn.png)

**Comment by Falconerd** [comment]
Awesome, I'll take a look at this. Thanks for letting me know,
