### ISSUE TITLE
My discord bot isn't sending messages from that channel to the other channel

### ISSUE THREAD

**Issue by SKTG-stack** [Falconerd/discord-bot-github#96]
I was making a discord bot that sends messages from one channel to another but this isn't working and I am not getting any errors
`@client.event
async def on_message(message):
    if discord.Message.channel == "940102892042481715":
        channel = client.get_channel(929233094244974602)
        await channel.send(message.content)`

**Comment by Falconerd** [comment]
This repo is for a 3rd party bot that uses the discord API to send messages about github updates. You may be able to find help with this query on the official site: https://discord.com/developers/docs
